version: 2

updates:
  # node.js modules
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    groups:
      lerna-lite:
        patterns:
          - "@lerna-lite/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: CI"
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"
