name: Cleanup caches for closed branch

permissions:
  actions: write

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Cleanup Cache
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup gh-action-cache
        run: |
          gh extension install actions/gh-action-cache

      - name: Cleanup cache
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh action-cache list -R ${REPO} -B ${BRANCH} | cut -f 1)

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in ${cacheKeysForPR}; do
            gh action-cache delete ${cacheKey} -R ${REPO} -B ${BRANCH} --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: refs/pulls/${{ github.event.pull_request.number }}/merge
