name: Lint (Node.js package)

on:
  pull_request:
    types: [opened, ready_for_review, review_requested]
    paths:
      [
        "pnpm-lock.yaml",
        "**/package.json",
        "**/tsconfig.json",
        "packages/**/*.js",
        "packages/**/*.ts"
      ]
  push:
    branches: [main]

permissions:
  checks: write
  contents: read

jobs:
  install:
    name: Install dependency
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest

      - name: Install pnpm and dependencies
        uses: ./.github/actions/setup-pnpm

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest

      - name: Install pnpm and dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.5

      - name: Run eslint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run lint |
          reviewdog -f eslint -name "Lint report" -reporter github-check -level warning
