name: Test (Node.js package)

on:
  pull_request:
    types: [opened, ready_for_review, review_requested]
    paths:
      [
        "pnpm-lock.yaml",
        "**/package.json",
        "**/tsconfig.json",
        "packages/**/*.js",
        "packages/**/*.ts"
      ]
  push:
    branches: [main]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/setup-pnpm

  test:
    name: Test (nodejs-${{ matrix.node-version }} on ${{ matrix.os }})
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16, 18, latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Run test
        run: |
          pnpm run test:coverage --reporter junit --outputFile ./result.xml --reporter basic

      - name: Report test result
        if: ${{ (success() || failure()) }}
        uses: mikepenz/action-junit-report@v3.8.0
        with:
          check_name: Test result (nodejs-${{ matrix.node-version }} on ${{ matrix.os }})
          report_paths: ./result.xml

      - name: Report test coverage
        if: ${{ (success() || failure()) && (github.event_name == 'pull_request') && (matrix.os == 'ubuntu-latest') && (matrix.node-version == 'latest') }}
        uses: davelosert/vitest-coverage-report-action@v2.1.1
        with:
          vite-config-path: ./vitest.workspace.js
