name: Test (Node.js package)

on:
  pull_request:
    types: [opened, ready_for_review, review_requested]
    paths:
      [
        "pnpm-lock.yaml",
        "**/package.json",
        "**/tsconfig.json",
        "packages/**/*.js",
        "packages/**/*.ts"
      ]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  install:
    name: Install dependency
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install pnpm and dependencies
        uses: ./.github/actions/setup-pnpm

  test:
    name: Test for nodejs-${{ matrix.node-version }} on ${{ matrix.os }}
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16, 18, latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm and dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Run test
        run: |
          pnpm run test --ci --reporters github-actions --silent

  generate-coverage:
    name: Generate coverage
    needs: install
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install pnpm and dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Run test and generate coverage
        continue-on-error: true
        run: |
          pnpm run test:coverage

      - name: Report coverage
        continue-on-error: true
        uses: davelosert/vitest-coverage-report-action@v2
